// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

[PrimaryKey("CustomerID", "CustomerTypeID")]
[Table("CustomerCustomerDemo")]
public partial class CustomerCustomerDemo
{
    [Key]
    [StringLength(5)]
    public string CustomerID { get; set; } = null!;

    [Key]
    [StringLength(10)]
    public string CustomerTypeID { get; set; } = null!;

    [ForeignKey("CustomerID")]
    [InverseProperty("CustomerCustomerDemos")]
    public virtual Customer Customer { get; set; } = null!;

    [ForeignKey("CustomerTypeID")]
    [InverseProperty("CustomerCustomerDemos")]
    public virtual CustomerDemographic CustomerType { get; set; } = null!;
}