// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

[PrimaryKey("EmployeeID", "TerritoryID")]
public partial class EmployeeTerritory
{
    [Key]
    public int EmployeeID { get; set; }

    [Key]
    [StringLength(20)]
    public string TerritoryID { get; set; } = null!;

    [ForeignKey("EmployeeID")]
    [InverseProperty("EmployeeTerritories")]
    public virtual Employee Employee { get; set; } = null!;

    [ForeignKey("TerritoryID")]
    [InverseProperty("EmployeeTerritories")]
    public virtual Territory Territory { get; set; } = null!;
}