// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DbFirst.Models
{
    public partial class sp_employees_rankResult
    {
        public string? Title { get; set; }
        public int EmployeeID { get; set; }
        public string FirstName { get; set; } = default!;
        [Column("Salary", TypeName = "decimal(18,2)")]
        public decimal? Salary { get; set; }
        public long? RANKS { get; set; }
    }
}
