// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DbFirst.Models;

public partial class Territory
{
    [Key]
    [StringLength(20)]
    public string TerritoryID { get; set; } = null!;

    [StringLength(50)]
    public string TerritoryDescription { get; set; } = null!;

    public int RegionID { get; set; }

    [InverseProperty("Territory")]
    public virtual ICollection<EmployeeTerritory> EmployeeTerritories { get; set; } = new List<EmployeeTerritory>();

    [ForeignKey("RegionID")]
    [InverseProperty("Territories")]
    public virtual Region Region { get; set; } = null!;
}